export * from './pages/home'
export * from './pages/login'
export * from './pages/register'
export * from './pages/dashboard'
export * from './pages/documents'
export * from './pages/contacts'
export * from './pages/settings'
